/** Declaration file generated by dts-gen */

declare module 'app-root-dir' {

  export function get(): any;

  export function set(dir: any): void;

  export namespace get {
    const prototype: {};

  }

  export namespace set {
    const prototype: {};

  }
}
